server:
  port: 8080
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/saturno
    username: postgres
    password: leonan2knet
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

